# Loading Data

In [1]:
import json
import ast 
import pandas as pd
import numpy as np
from IPython import display
data = []
fracture = pd.read_csv("groupedProportionFracture.csv") # Fracture Data
pd.set_option('display.max_rows', 1000)


In [2]:
# Loading Chat Data
for _ in set(fracture["batch"]):
    with open('../.data/' + str(_) + "/chats.json", "r") as f:
        chat = json.load(f)
        data.append(chat)
                

In [4]:
data[0] # View Json files loaded

[{'room': 'B',
  'userID': 'IwWtxwhI35NnmrJtAAAK',
  'message': 'I keep combing, but nothing sounds as catchy',
  'time': 383.52,
  'batch': 1535567328002,
  'round': 1,
  '_id': '0tQ7DQLNFiMc8aCN',
  'createdAt': '2018-08-29T18:52:58.598Z',
  'updatedAt': '2018-08-29T18:52:58.598Z'},
 {'room': 'B',
  'userID': 'GaSMgpnu8XnFLFEIAAAE',
  'message': 'They seem to have a streamlined, futuristic image.  ',
  'time': 350.009,
  'batch': 1535567328002,
  'round': 0,
  '_id': '1raKI43Dy2tndLVL',
  'createdAt': '2018-08-29T18:40:52.257Z',
  'updatedAt': '2018-08-29T18:40:52.257Z'},
 {'room': 'A',
  'userID': 'yX8iMHt25uZsiw1vAAAW',
  'message': 'ohh, I like yours better',
  'time': 391.388,
  'batch': 1535567328002,
  'round': 2,
  '_id': '3ApatQoxlIefE5RW',
  'createdAt': '2018-08-29T19:04:00.740Z',
  'updatedAt': '2018-08-29T19:04:00.740Z'},
 {'room': 'B',
  'userID': 'GaSMgpnu8XnFLFEIAAAE',
  'message': 'Okay.  I like what you said, IwWtxwhI35NnmrJtAAAK but do you think it fits the company 

In [138]:
fracture # Fracture data

Unnamed: 0 room          batch  round condition results.condition  \
0             1    A  1534356049092      1         A         treatment   
1             2    A  1534356049092      2         B         treatment   
2             3    A  1534356049092      3        Ap         treatment   
3             4    A  1534883331480      1         A         treatment   
4             5    A  1534883331480      3        Ap         treatment   
5             6    A  1534893597484      1         A         treatment   
6             7    A  1534893597484      3        Ap         treatment   
7             8    A  1534965856368      2         B         treatment   
8             9    A  1535036462235      1         B           control   
9            10    A  1535043662301      3         B           control   
10           11    A  1535046705869      1         A         treatment   
11           12    A  1535046705869      3        Ap         treatment   
12           13    A  1535053364227      3         C          baseline   
13           14    A  1535133781647      1         A          baseline   
14           15    A  1535151954966      2         A           control   
15           16    A  1535151954966      3        Ap           control   
16           17    A  1535399280044      2         B          baseline   
17           18    A  1535399280044      3         C          baseline   
18           19    A  1535400139560      1         A          baseline   
19           20    A  1535400139560      2         B          baseline   
20           21    A  1535414573971      2         B          baseline   
21           22    A  1535465389122      1         A         treatment   
22           23    A  1535465389122      2        Ap         treatment   
23           24    A  1535465389122      3         B         treatment   
24           25    A  1535469595211      1         B         treatment   
25           26    A  1535485838343      3         B         treatment   
26           27    A  1535499714883      2         B          baseline   
27           28    A  1535506770832      1         A         treatment   
28           29    A  1535506770832      2        Ap         treatment   
29           30    A  1535508140527      2         A           control   
30           31    A  1535508140527      3        Ap           control   
31           32    A  1535567328002      1         A          baseline   
32           33    A  1535567328002      3         C          baseline   
33           34    A  1535575374559      1         A          baseline   
34           35    A  1535575374559      2         B          baseline   
35           36    A  1535576148516      1         B           control   
36           37    A  1535579642917      1         B           control   
37           38    A  1535583912307      3         C          baseline   
38           39    A  1535587309558      2         B          baseline   
39           40    A  1535587309558      3         C          baseline   
40           41    A  1535587845707      2         B          baseline   
41           42    A  1535641262001      1         A          baseline   
42           43    A  1535644862176      3         B           control   
43           44    A  1535662860294      1         A          baseline   
44           45    A  1535662860294      3         C          baseline   
45           46    A  1535664584229      1         A           control   
46           47    A  1535664584229      3        Ap           control   
47           48    B  1534887745334      1         A         treatment   
48           49    B  1534887745334      2         B         treatment   
49           50    B  1534887745334      3        Ap         treatment   
50           51    B  1534893597484      2         B         treatment   
51           52    B  1534894490335      1         A         treatment   
52           53    B  1534894490335      3        Ap         treatment   
53       

In [141]:
import numpy as np
def getfracture(row, fracture, batchID):
    f = fracture[(fracture["batch"] == batchID)  & (fracture["room"] == row["team"]) & (fracture["round"] == row["round"])]["fracture"]
    if (list(f)==[0]):
        return 0
    elif (list(f)==[]):
        return np.nan
    else:
        return 1



# Splitting Data into Interactions

In [159]:
frame = {}
for _ in data:
    print ("Batch", _[0]["batch"])
    batch = [(chat["round"] + 1, chat["room"], chat["userID"], chat["message"], chat["time"], 0) 
                      for chat in _]
    batch = pd.DataFrame(batch)
    batch.columns = ["round", "team", "userID", "message", "time", "fracture"]
    batch = batch.sort_values(["round", "team", "time"])
    batch = batch[batch["team"] != ""]
    batch["fracture"] = batch.apply(getfracture, args=(fracture, _[0]["batch"]), axis = 1)
    batch.index = np.arange(1, batch.shape[0] + 1)
    for index, row in batch.iterrows():
        identifier = tuple([_[0]["batch"], row["round"], row["team"]])
        if identifier not in frame.keys():
            frame[identifier] = {"message": [row["message"]], "fracture": row["fracture"]}
        else:
            frame[identifier]["message"].append(row["message"])

        
    

Batch 1535567328002
Batch 1535053364227
Batch 1535662860294
Batch 1535485838343
Batch 1535133781647
Batch 1535506770832
Batch 1535487963026
Batch 1535414573971
Batch 1535151954966
Batch 1534883331480
Batch 1535467359000
Batch 1535036462235
Batch 1535504829981
Batch 1535576148516
Batch 1535579642917
Batch 1535664584229
Batch 1535400139560
Batch 1535570157353
Batch 1534893597484
Batch 1535399280044
Batch 1535641262001
Batch 1534887745334
Batch 1534980081847
Batch 1535483304119
Batch 1535397094585
Batch 1535590236737
Batch 1535465389122
Batch 1535499714883
Batch 1534356049092
Batch 1534983421384
Batch 1534961821513
Batch 1535469595211
Batch 1535587845707
Batch 1535046705869
Batch 1535497021009
Batch 1535043662301
Batch 1535575374559
Batch 1535644862176
Batch 1534894490335
Batch 1535391659879
Batch 1534896122348
Batch 1535508140527
Batch 1534965856368
Batch 1535583912307
Batch 1535587309558


In [160]:
frame

{(1535567328002,
  1,
  'A'): {'message': ['hello',
   'hello',
   "I'm off to read the link..brb",
   'Ok, what about this. KOSMOS ink - The magnetic fountain pen of the future',
   'I like it ',
   'or "A fountain pen that will never loose it\'s cap or roll off the table" <--there\'s gotta be a catchier way to say that',
   'I like the first one better maybe we can add something to that one.',
   "KOSMOS ink - The magnetic fountain pen of the future that won't roll away",
   'Ah, that\'s nice.  What about Ok, what about this. "KOSMOS ink - The magnetic fountain pen of the future that stays where you put it"',
   'I think that is even better',
   'or should we just leave "of the future" out of it?',
   'zXDetzhy_jwSwtllAAAa are you even here?',
   'I like having of the future in it',
   "cool. Ok, we'll go with that unless yall can think of something better in the next 2 minutes",
   'I think we should use that one',
   'Ok, I will type it in',
   'KOSMOS ink - The magnetic fountain p

In [181]:
chats = [(val["message"]) for key, val in frame.items() if not np.isnan(val["fracture"])]
fractures = [val["fracture"] for key, val in frame.items() if not np.isnan(val["fracture"])]
print(chats[30])
print(fractures[30])

['Hi there', 'Hello', 'Just watchin the video and gaining info', 'So the company is LIV', 'Yes', 'I was thinking we could use the word life--like "LIV. Life in titanium."', 'LIV - Swiss Quality Perfected', 'Oh, I like that idea', 'or using your idea, like "LIV Perfect."', 'I love LIV Perfect', 'They really seem to like the materials', 'Yeah seems very high quality', 'And detailed', '"LIV life to the maximum."', 'LIV - Life to the Maximum', 'yeah, sounds good', 'Sounds really good', '!LIV -- Life to the Maximum.', '!LIV - Life to the Maximum.']
0.0


Define a class that will be our bag of words mapper.

In [249]:
class Lang:
    def __init__(self):
        self.word2index = {}
        self.index2word = {}
        self.n_words = 0  # Count SOS and EOS
        self.word2count = {}

#     def addSentence(self, sentence):
#         for word in sentence.split(' '):
#             self.addWord(word)

    def addWord(self, word):
        if word not in self.word2index:
            self.word2index[word] = self.n_words
            self.index2word[self.n_words] = word
            self.word2count[word] = 1
            self.n_words += 1
        else:
            self.word2count[word] += 1
            
        

Create a bag of words representation

In [250]:
word2index = {}
tokenize = Lang()
for _ in chats:
    words_messages = [message.split(" ") for message in _]
    
    word_list = []
    for words in words_messages:
        word_list.extend(words)
    words_messages = word_list
    for char in ",.!?": # remove punctuation marks (count punctuation as same as words)
        words_messages = [message.split(char) for message in words_messages]
        words_messages = [item for sublist in words_messages for item in sublist]

    for char in "<-'":
        words_messages = [message.replace(char, "") for message in words_messages]
            
   
    words_messages = [message.lower() for message in words_messages]
    print (words_messages)
    for word in words_messages:
        tokenize.addWord(word)
    


['hello', 'hello', 'im', 'off', 'to', 'read', 'the', 'link', '', 'brb', 'ok', '', 'what', 'about', 'this', '', 'kosmos', 'ink', '', 'the', 'magnetic', 'fountain', 'pen', 'of', 'the', 'future', 'i', 'like', 'it', '', 'or', '"a', 'fountain', 'pen', 'that', 'will', 'never', 'loose', 'its', 'cap', 'or', 'roll', 'off', 'the', 'table"', 'theres', 'gotta', 'be', 'a', 'catchier', 'way', 'to', 'say', 'that', 'i', 'like', 'the', 'first', 'one', 'better', 'maybe', 'we', 'can', 'add', 'something', 'to', 'that', 'one', '', 'kosmos', 'ink', '', 'the', 'magnetic', 'fountain', 'pen', 'of', 'the', 'future', 'that', 'wont', 'roll', 'away', 'ah', '', 'thats', 'nice', '', '', 'what', 'about', 'ok', '', 'what', 'about', 'this', '', '"kosmos', 'ink', '', 'the', 'magnetic', 'fountain', 'pen', 'of', 'the', 'future', 'that', 'stays', 'where', 'you', 'put', 'it"', 'i', 'think', 'that', 'is', 'even', 'better', 'or', 'should', 'we', 'just', 'leave', '"of', 'the', 'future"', 'out', 'of', 'it', '', 'zxdetzhy_jwswtl

In [368]:
X = []
for _ in chats:
    words_messages = [message.split(" ") for message in _]
    
    word_list = []
    for words in words_messages:
        word_list.extend(words)
    words_messages = word_list
    for char in ",.!?":
        words_messages = [message.split(char) for message in words_messages]
        words_messages = [item for sublist in words_messages for item in sublist]

    for char in "<-'":
        words_messages = [message.replace(char, "") for message in words_messages]
            
   
    words_messages = [message.lower() for message in words_messages]

    bago_words = np.zeros(tokenize.n_words,)
    for word in words_messages:
        bago_words[tokenize.word2index[word]] += 1
    X.append(bago_words)
    

In [369]:
X = np.array(X)
Y = np.array(fractures)

In [370]:
X[0]

array([2., 1., 2., ..., 0., 0., 0.])

In [371]:
Y

array([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.])

In [372]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print (X_train.shape)


(144, 2608)


In [373]:
from sklearn.model_selection import KFold, cross_val_score

for _ in range(1, 50, 10):
    k_fold = KFold(n_splits=5, shuffle=True)
    knn = KNeighborsClassifier(n_neighbors=_, weights='distance')
    print(_, cross_val_score(knn, X_train, y_train, cv=k_fold, n_jobs=-1))


1 [0.5862069  0.31034483 0.62068966 0.48275862 0.46428571]
11 [0.62068966 0.37931034 0.51724138 0.51724138 0.60714286]
21 [0.62068966 0.51724138 0.4137931  0.51724138 0.53571429]
31 [0.68965517 0.44827586 0.48275862 0.62068966 0.60714286]
41 [0.37931034 0.5862069  0.48275862 0.55172414 0.53571429]


In [374]:
from sklearn.linear_model import LogisticRegression

k_fold = KFold(n_splits=5, shuffle=True)
lr = LogisticRegression()
print(_, cross_val_score(lr, X_train, y_train, cv=k_fold, n_jobs=-1))

41 [0.55172414 0.55172414 0.4137931  0.44827586 0.67857143]


In [375]:
from sklearn import svm
for _ in np.linspace(0.1, 10, 5):
    sv = svm.SVC(kernel='rbf', C = _)
    scores = cross_val_score(sv, X_train, y_train, cv=k_fold, n_jobs=-1)
    print(_, scores, np.mean(scores))

0.1 [0.5862069  0.5862069  0.48275862 0.62068966 0.46428571] 0.5480295566502463
2.575 [0.48275862 0.55172414 0.65517241 0.5862069  0.60714286] 0.5766009852216749
5.05 [0.44827586 0.65517241 0.48275862 0.68965517 0.5       ] 0.5551724137931034
7.525 [0.48275862 0.55172414 0.51724138 0.65517241 0.42857143] 0.5270935960591132
10.0 [0.5862069  0.55172414 0.51724138 0.4137931  0.5       ] 0.5137931034482758


In [376]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=1000)
# rf.fit(X_train, y_train)
scores = cross_val_score(sv, X_train, y_train, cv=k_fold, n_jobs=-1)
# print(accuracy_score(rf.predict(X_test), y_test))
print (scores, np.mean(scores))

[0.68965517 0.51724138 0.4137931  0.37931034 0.53571429] 0.5071428571428571


In [324]:
print (y_test)

[1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1.
 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]


In [379]:
from sklearn.decomposition import PCA
pca = PCA(n_components=100)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=100, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [381]:
print(pca.explained_variance_ratio_)  
print(pca.singular_values_)  

[0.40885701 0.05772623 0.02608501 0.02172225 0.02076213 0.01743907
 0.01488972 0.0135443  0.01316903 0.01240827 0.01142612 0.01118145
 0.0105373  0.00971683 0.00952498 0.00900531 0.00852309 0.00814572
 0.00755339 0.00728357 0.00698094 0.00660216 0.00644004 0.00590864
 0.00582397 0.0056494  0.00560461 0.00525046 0.00519227 0.00503634
 0.00499666 0.00487793 0.00478492 0.00468502 0.00454063 0.00439651
 0.00430091 0.00418611 0.00413158 0.00404346 0.00396068 0.00390476
 0.00376266 0.0036859  0.00354191 0.00346771 0.00341482 0.00335071
 0.00331057 0.00321835 0.00317348 0.0031139  0.00306198 0.0029721
 0.00293167 0.00287904 0.00287316 0.00280113 0.0027588  0.00273896
 0.00264997 0.00258858 0.0025184  0.00249546 0.00244    0.00237189
 0.00233873 0.00228514 0.00224253 0.0021942  0.00215975 0.00210176
 0.00210024 0.0020553  0.00200781 0.00199976 0.00188735 0.00183702
 0.0017973  0.00176611 0.00175281 0.00171827 0.00170045 0.00167189
 0.00163791 0.00162333 0.00159556 0.00156347 0.00154892 0.00150

In [395]:
print(X.shape)
X_ = (pca.transform(X))
X_train, X_test, y_train, y_test = train_test_split(X_, Y, test_size=0.2)

(181, 2608)


In [401]:
for _ in range(1, 50, 10):
    k_fold = KFold(n_splits=5, shuffle=True)
    knn = KNeighborsClassifier(n_neighbors=_, weights='distance')
    print(_, cross_val_score(knn, X_train, y_train, cv=k_fold, n_jobs=-1))
lr = LogisticRegression()
print(_, cross_val_score(lr, X_train, y_train, cv=k_fold, n_jobs=-1))
for _ in np.linspace(0.1, 10, 5):
    sv = svm.SVC(kernel='rbf', C = _)
    scores = cross_val_score(sv, X_train, y_train, cv=k_fold, n_jobs=-1)
    print(_, scores, np.mean(scores))
rf = RandomForestClassifier(n_estimators=1000)
# rf.fit(X_train, y_train)
scores = cross_val_score(sv, X_train, y_train, cv=k_fold, n_jobs=-1)
# print(accuracy_score(rf.predict(X_test), y_test))
print (scores, np.mean(scores))

1 [0.48275862 0.44827586 0.5862069  0.55172414 0.42857143]
11 [0.4137931  0.51724138 0.5862069  0.44827586 0.39285714]
21 [0.44827586 0.44827586 0.62068966 0.51724138 0.53571429]
31 [0.62068966 0.44827586 0.55172414 0.44827586 0.46428571]
41 [0.5862069  0.5862069  0.44827586 0.68965517 0.39285714]
41 [0.44827586 0.51724138 0.51724138 0.5862069  0.5       ]
0.1 [0.5862069  0.62068966 0.62068966 0.4137931  0.57142857] 0.5625615763546797
2.575 [0.5862069  0.44827586 0.44827586 0.5862069  0.46428571] 0.5066502463054187
5.05 [0.51724138 0.65517241 0.27586207 0.34482759 0.46428571] 0.4514778325123153
7.525 [0.5862069  0.37931034 0.51724138 0.5862069  0.53571429] 0.520935960591133
10.0 [0.48275862 0.51724138 0.44827586 0.37931034 0.60714286] 0.48694581280788174
[0.31034483 0.55172414 0.44827586 0.55172414 0.57142857] 0.48669950738916257
